on:
  workflow_dispatch:
name: build
jobs:
  build:
    name: compile
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cURL Headers
        run: curl https://curl.se/download/curl-8.14.1.tar.gz | sudo tar xz -C /usr --strip-components=1 curl-8.14.1/include
        env:
          V: 7.58.0
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
      - name: setup haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: false
      - name: build c code
        run: bash ./compile
      - name: build hs code
        run: cabal build --allow-newer=base
      - name: archive
        run: tar cf freearc.tar .
      - uses: actions/upload-artifact@v4
        with:
          path: freearc.tar
