on: 
  push
  workflow_dispatch:  

name: build
jobs:
  build:
    name: compile
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
      - name: setup haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: false
      - name: build c code
        run: bash ./compile
      - name: build hs code
        run: cabal build
      - name: archive
        run: tar cf freearc.tar .
      - uses: actions/upload-artifact@v4
        with:
          path: freearc.tar
